export const isDevelopment = process.env.NODE_ENV !== 'production';
export const entityTypeRegex = /(actions|enemies|features|items|locations|maps|persons|quests)/;
export const entityNameRegex = /^[a-zA-Z][A-Za-z0-9_]+$/;
export const IdProperty: string = 'id';
export const TypeProperty: string = 'type';
export const Features: string = 'features';
export const Quests: string = 'quests';
export const Items: string = 'items';
export const Enemies: string = 'enemies';
export const Persons: string = 'persons';
export const Locations: string = 'locations';
export const Maps: string = 'maps';
export const Characters: string = 'characters';
export const GameStateSave: string = "gameState";
export const SaveGamePrefix: string = "SaveGame_";
export const HighScores: string = 'highScores';
export const DescriptionProperty: string = 'description';