import { IInterfaceTexts } from 'storyScript/Interfaces/storyScript';

export function CustomTexts(): IInterfaceTexts {
    return {
        newGame: "Nieuw spel",
        startAdventure: "Start avontuur",
        nextQuestion: "Volgende vraag",
        equipmentHeader: "Uitrusting",
        gameName: "Gevaarlijke grot",
        saveGame: "Spel opslaan",
        loadGame: "Laad spel",
        loadSaveGame: "Laad spel {0}",
        youAreHere: "Je bent hier: {0}",
        destinations: "Reizen",
        onTheGround: "Op de grond",
        hitpoints: "Gezondheid",
        currency: "Geld",
        messages: "Gebeurtenissen",
        backpack: "Rugzak",
        back: "Terug: ",
        attack: "Val {0} aan!",
        startOver: "Begin overnieuw",
        resetWorld: "Reset wereld",
        actions: "Acties",
        head: "Hoofd:",
        amulet: "Amulet:",
        body: "Lichaam:",
        rightHand: "Rechterhand:",
        leftHand: "Linkerhand:",
        legs: "Benen:",
        feet: "Voeten:",
        enemies: "Vijanden",
        loading: "Laden...",
        equip: "Gebruiken",
        use: "Gebruiken",
        drop: "Weg doen",
        levelUp: "Je wordt hier beter in!",
        completeLevelUp: "Ok",
        levelUpDescription: "Je hebt niveau {0} bereikt.",
        encounters: "Vijanden",
        combatTitle: "Gevecht",
        combatWin: "Je hebt gewonnen!",
        mainMenu: "Hoofdmenu",
        confirmRestart: "Echt overnieuw beginnen?",
        restartConfirmed: "Ja",
        restartCancelled: "Nee",
        existingSaveGames: "Opgeslagen spellen",
        newSaveGame: "Nieuw spel opslaan",
        save: "Opslaan",
        load: "Laden",
        cancel: "Annuleren",
        youLost: "Je hebt verloren!",
        highScores: "Topscores:",
        questFailed: "Je hebt gefaald...",
        finalScore: "Je score: ",
        tryAgain: "Nog eens proberen",
        view: "Bekijken"
    };
}