import './locations/start'
import './locations/bedroom'
import './locations/Garden'
import './locations/DirtRoad'
import './locations/Basement'
import './enemies/bandit'
import './items/basementKey'
import './items/journal'
import './items/leatherBoots'
import './items/sword'
import './persons/Friend'
import './quests/journal'
import { registrationDone } from '../../Engine/ObjectConstructors'

registrationDone();